name = "dont-drop-him-online"
main = "src/index.js"
compatibility_date = "2026-08-01"

[[durable_objects.bindings]]
name = "ROOMS"
class_name = "RoomDO"

[[durable_objects.bindings]]
name = "LOBBY"
class_name = "LobbyDO"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["RoomDO"]

[[migrations]]
tag = "v2"
new_sqlite_classes = ["LobbyDO"]
